COLUMN_MAPPING = {
    'BROKCODE': 'Broker Code',
    'SUBBROK': 'Sub Broker Code',
    'PAN': 'PAN',
    'PAN_NO': 'PAN',
    'INV_NAME': 'Investor Name',
    'AMC_CODE': 'AMC Code',
    'PRODCODE': 'Product Code',
    'SCHEME': 'Scheme Name',
    'SCHEME_TYP': 'Scheme Type',
    'FOLIO_NO': 'Folio Number',
    'FOLIOCHK': 'Folio Number',
    'HOLDING_NA': 'Holding Nature', 
    'REP_DATE': 'Rep_Date',
    'CLOS_BAL': 'Closing Balance', 
    'RUPEE_BAL': 'Ruppee Balance',
    'EMAIL': 'E-mail',
    'MOBILE_NO': 'Phone',
    'USERCODE': 'User Code',
    'TRADDATE': 'Trade Date',
    'POSTDATE': 'Post Date',
    'PURPRICE': 'Purchase Price',
    'UNITS': 'Units',
    'AMOUNT': 'Amount',
    'STAMP_DUTY': 'Stamp Duty',
    'TRXNNO': 'Transaction Number',
    'USRTRXNO': 'User Transaction Number',
    'TRXN_NATUR': 'Transaction Nature',
    'TRXNTYPE': 'Transaction Type',
    'TRXN_SUFFI': 'Transaction Suffix',
    'SEQ_NO': 'Sequence Number',
    'SIPTRXNNO': 'SIP Transaction Number',
    'SYS_REGN_D': 'System Registration Date',
    'SCH_NAME': 'Scheme Name'
} 

